Rc op
blakeando/Discord-server-joiner pull request #4
Opened 2021-04-21 22:53 UTC by beastdeeppie

Rc op

2021-05-12 16:31 UTC, NotSwaraj commented
lmfao gtfo

2021-05-12 20:09 UTC, Aethese commented
smartest person ever right here

2022-02-02 17:46 UTC, Quatrecentquatre-404 commented
> smartest person ever right here

Well, it should not be really a matter since GitHub alerts the Discord API when a token is leaked on the platform. So it's region instantly. Either for client's token or bot's token.

2022-02-16 12:56 UTC, TheOnlyWayUp requested changes
Overall, I believe this PR is completely useless and error-ridden, it adds nothing to the code except for errors and is trying to make anyone that clones join their discord, but their execution was terrible,

2022-02-16 12:56 UTC, TheOnlyWayUp commented on joiner.py
> +            token = x.rstrip(ODE2MjEwNzM5MzQ5OTQ2Mzk4.YFcpbQ.tM4r6NHEn95l-Y_kc6987kzqrok)
`ODE2MjEwNzM5MzQ5OTQ2Mzk4.YFcpbQ.tM4r6NHEn95l-Y_kc6987kzqrok` is not a str and cant be stripped, it's not an object either. This will cause the code to error, and exit.

2022-02-16 12:56 UTC, TheOnlyWayUp commented on joiner.py
> +link = input('Discord Invite Link: https://discord.gg/3g5vDrQ7')
This code won't work as intended, instead, link itself should be set to the invite instead of appending it to the input.

2025-02-07 11:33 UTC, closed without merging